### PR TITLE
Failing tests because of incompatibility of recent MVVM changes and button#noText

### LINKED ISSUE #25: Failing tests because of incompatibility of recent MVVM changes and button#noText
That property needs to be passed to button's view model (introduced in #23). And this turns to be tricky, because it means that it needs to be defined everywhere now, because bindings don't allow you to bind to a non-existence property. IMO, the latter is an unnecessary check – bindings should work with undefined props as well. Then fixing this issue would be super simple.

### PR DESCRIPTION
**Pull request by oleq**
Fixes #25. Requires https://github.com/ckeditor/ckeditor5-utils/pull/46.

### CODE REVIEW

File: tests/button/buttonview.js [hunk 1]
```diff
@@ -99,20 +99,4 @@ describe( 'ButtonView', () => {
 			} );
 		} );
 	} );
-
-	describe( '_setupIcon', () => {
```
Comment (Reinmar) [inline tests/button/buttonview.js:103]: Why was this test removed? Is this functionality covered by some other one?

Comment (oleq) [inline tests/button/buttonview.js:103]: Yep. It's the same as https://github.com/ckeditor/ckeditor5-ui-default/blob/d6c6f31bc0acfeabdb0f5592ed2df3269f4a5b27/tests/button/button.js#L74-L87 isn't it? It's a regression after #23.

Comment (oleq) [inline tests/button/buttonview.js:103]: Besides, there's no more `_setupIcon` method in the class.
